app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, template_folder="templates", static_folder="static")

from app.main import routes

app/main/routes.py
from flask import render_template
from bs4 import BeautifulSoup
from app.models import Content
from app import db
from . import bp


@bp.errorhandler(404)
def not_found_error(error):
    return render_template("404.html"), 404


@bp.route("/")
@bp.route("/index")
def index():
    content = Content.query.all()
    return render_template("index.html", content=content)


@bp.route("/content<int:id>", methods=["GET", "POST"])
def content(id):
    post = db.session.query(Content).get(id)
    if post.content:
        post.content = BeautifulSoup(post.content, "html.parser")
    return render_template("content.html", post=post)

app/main/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
        {{ title }}
        {% endif %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{{ url_for('main.static', filename='css/styles.css') }}">-->
    {% block styles %}{% endblock %}
    <script src="https://kit.fontawesome.com/3c7e38d30f.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-md">
        <nav class="navbar navbar-expand-lg navbar-dark bg-black">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('editor.editor') }}">Editor</a>
                        </li>
                    </ul>
                    <nav class="navbar navbar-expand-sm">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa-brands fa-twitter" style="color: #ffffff;"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa-brands fa-github" style="color: #ffffff;"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa-brands fa-linkedin" style="color: #ffffff;"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa-brands fa-youtube" style="color: #ffffff;"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="fa-brands fa-instagram" style="color: #ffffff;"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </nav>
        <h1 id="page-title" class="mt-2">
            {% if page_title %}
            {{ page_title }}
            {% endif %}
        </h1>
        {% block content %}{% endblock %}
        <footer>
            <p>&copy; 2023 My Website</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

app/main/templates/content.html
{% extends "base.html" %}

{% block content %}
<a href="{{ url_for('editor.edit_post', id=post.id) }}"><button>Edit</button></a>
<h1>{{ post.title }}</h1>
{{ post.content|safe }}

{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>TEST</h1>
{% for post in content %}
{{ post.id }}
<a href="{{ url_for('main.content', id=post.id) }}">{{ post.title }}</a>
<p>{{ post.snippet }}</p>
{% endfor %}
{% endblock %}